### ISSUE TITLE
Broken links to legacy images WPF

### ISSUE THREAD

**Issue by BigBallard** [PrismLibrary/prismlibrary.github.io#9]
It appears that the links to the images have been broken for the WPF pages of the site.

**Comment by brianlagunas** [comment]
Well, its very strange because the images are there:

https://github.com/PrismLibrary/prismlibrary.github.io/blob/master/docs/wpf/legacy/images/Ch1IntroFig1.png

Not sure why its not working.

http://prismlibrary.github.io/docs/wpf/legacy/images/Ch1IntroFig1.png

**Comment by brianlagunas** [comment]
oh, it's magically working now.
